name: home_party
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  animated_text_kit: ^1.3.0
  cupertino_icons: ^0.1.3
  modal_progress_hud: ^0.1.3 
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.0
  smooth_star_rating: ^1.1.1
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.0+17
  image_cropper: ^1.0.2
  firebase_storage: ^3.0.3
  bottom_navy_bar: ^3.0.0
  circular_bottom_navigation: ^1.0.1
  firebase_image: ^0.1.6
  flutter_widgets: ^0.1.12
  ff_navigation_bar: ^0.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: Delius
      fonts:
        - asset: assets/fonts/DeliusUnicase-bold.ttf
    
  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - images/
